services:
  app:
    image: node:alpine
    command: sh -c "cd /app && npm install && sleep infinity"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app

  db: 
    image: mongo:latest
    command: sleep infinity
    volumes:
      - db-data:/data/db

  backend:
    image: node:alpine
    command: sleep infinity
    ports:
      - 3000:3000
    working_dir: /backend
    volumes:
      - ./backend:/backend

volumes:
  db-data: